version: 1
formatters:
  timeFormatter:
    style: '{'
    format: '{asctime} - {levelname:^8}: {message}'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: timeFormatter
    stream: ext://sys.stdout
  fileHandler:
    class: config_selection.append_file_handler.TimeFileHandler
    level: INFO
    formatter: timeFormatter
    filename: './config_selection/results/config_results_{}.log'
loggers:
  configLogger:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [consoleHandler]
